import { FormEvent, useMemo, useState } from 'react';
import { CheckCircle2, FolderKanban, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useLocalStorage } from '../hooks/useLocalStorage';

type Priority = 'low' | 'medium' | 'high';
type Status = 'planned' | 'active' | 'completed';
type Project = { id: string; title: string; description: string; deadline: string; priority: Priority; status: Status; progress: number; color: 'blue' | 'purple' | 'green' | 'orange' };
type Draft = Omit<Project, 'id'>;
const emptyDraft = (): Draft => ({ title: '', description: '', deadline: '', priority: 'medium', status: 'planned', progress: 0, color: 'blue' });
const colorClass: Record<Project['color'], string> = { blue: 'border-blue-500/40 bg-blue-500/10 text-blue-300', purple: 'border-purple-500/40 bg-purple-500/10 text-purple-300', green: 'border-safe/40 bg-safe/10 text-safe', orange: 'border-caution/40 bg-caution/10 text-caution' };
const priorityClass: Record<Priority, string> = { low: 'text-safe', medium: 'text-caution', high: 'text-panic' };

export default function Projects() {
  const [projects, setProjects] = useLocalStorage<Project[]>('neurospace_projects', []);
  const [query, setQuery] = useState('');
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const visible = useMemo(() => projects.filter((project) => `${project.title} ${project.description}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.status === 'completed' ? 1 : b.status === 'completed' ? -1 : a.deadline.localeCompare(b.deadline)), [projects, query]);
  const openNew = () => { setDraft(emptyDraft()); setEditingId(null); setError(''); setShowForm(true); };
  const edit = (project: Project) => { const { id, ...next } = project; setDraft(next); setEditingId(id); setError(''); setShowForm(true); };
  const save = (event: FormEvent) => { event.preventDefault(); if (!draft.title.trim()) { setError('Project title is required.'); return; } const next = { ...draft, title: draft.title.trim(), description: draft.description.trim() }; setProjects((current) => editingId ? current.map((project) => project.id === editingId ? { ...next, id: editingId } : project) : [...current, { ...next, id: crypto.randomUUID() }]); setShowForm(false); };
  const toggleComplete = (id: string) => setProjects((current) => current.map((project) => project.id === id ? { ...project, status: project.status === 'completed' ? 'active' : 'completed', progress: project.status === 'completed' ? project.progress : 100 } : project));
  return <div className="flex flex-col gap-8 font-mono pb-8 max-w-full overflow-x-hidden">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-gray-800 pb-4"><div><span className="text-[10px] text-gray-500 uppercase tracking-[0.3em] font-bold">Workstream Control</span><h1 className="text-white text-3xl md:text-4xl font-bold uppercase tracking-tight mt-1">Projects</h1><p className="text-gray-500 text-xs mt-2">Plan goals, track progress, and finish meaningful work.</p></div><button onClick={openNew} className="flex items-center gap-1.5 px-4 py-2 border border-gray-700 text-gray-300 text-[10px] uppercase tracking-wider hover:border-safe hover:text-safe self-start"><Plus size={12} /> New Project</button></div>
    <div className="flex items-center gap-2 px-3 py-2 border border-gray-800 bg-surface"><Search size={14} className="text-gray-600" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects..." className="w-full min-w-0 bg-transparent outline-none text-xs text-gray-200 placeholder-gray-600" /></div>
    {projects.length === 0 ? <section className="border-2 border-dashed border-gray-800 bg-surface/50 p-10 sm:p-14 text-center"><FolderKanban size={32} className="mx-auto text-gray-600 mb-5" /><h2 className="text-xl font-bold uppercase text-white">No projects yet.</h2><p className="text-gray-500 text-xs mt-3">Create a project to organize deadlines, priorities, notes, and progress.</p><button onClick={openNew} className="mt-7 inline-flex items-center gap-2 px-6 py-3 border border-safe text-safe text-[10px] font-bold uppercase tracking-widest hover:bg-safe/10"><Plus size={14} /> Create Project</button></section> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{visible.map((project) => <article key={project.id} className={`border-l-4 border-t border-r border-b border-gray-800 bg-surface p-5 ${project.status === 'completed' ? 'opacity-60' : ''}`}><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex gap-2 flex-wrap mb-2"><span className={`px-1.5 py-0.5 border text-[9px] uppercase ${colorClass[project.color]}`}>{project.status}</span><span className={`text-[9px] uppercase ${priorityClass[project.priority]}`}>{project.priority} priority</span></div><h2 className="font-bold text-white text-lg break-words">{project.title}</h2></div><div className="flex gap-1"><button onClick={() => toggleComplete(project.id)} className="w-8 h-8 border border-gray-700 text-gray-500 hover:text-safe hover:border-safe"><CheckCircle2 size={14} /></button><button onClick={() => edit(project)} className="w-8 h-8 border border-gray-700 text-gray-500 hover:text-safe hover:border-safe"><Pencil size={13} /></button><button onClick={() => setProjects((current) => current.filter((item) => item.id !== project.id))} className="w-8 h-8 border border-gray-700 text-gray-500 hover:text-panic hover:border-panic"><Trash2 size={13} /></button></div></div><p className="text-gray-500 text-xs mt-3 min-h-8">{project.description || 'No project notes yet.'}</p><div className="mt-5"><div className="flex justify-between text-[10px] text-gray-500 mb-1"><span>Progress</span><span>{project.progress}%</span></div><div className="h-1.5 bg-void"><div className="h-full bg-safe" style={{ width: `${project.progress}%` }} /></div></div><div className="mt-4 text-[10px] text-gray-500">{project.deadline ? `Deadline: ${project.deadline}` : 'No deadline set'}</div></article>)}</div>}
    {showForm && <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-lg max-h-[90vh] overflow-y-auto bg-void border-2 border-gray-800 p-6 space-y-3"><h2 className="text-white font-bold uppercase">{editingId ? 'Edit Project' : 'New Project'}</h2><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Project title" className="w-full bg-surface border border-gray-800 p-2 text-xs text-white outline-none focus:border-safe" /><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Notes" className="w-full min-h-24 bg-surface border border-gray-800 p-2 text-xs text-white outline-none focus:border-safe" /><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><input type="date" value={draft.deadline} onChange={(event) => setDraft({ ...draft, deadline: event.target.value })} className="bg-surface border border-gray-800 p-2 text-xs text-white" /><select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as Priority })} className="bg-surface border border-gray-800 p-2 text-xs text-white"><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select></div><label className="block text-[10px] text-gray-500 uppercase">Progress {draft.progress}%<input type="range" min="0" max="100" value={draft.progress} onChange={(event) => setDraft({ ...draft, progress: Number(event.target.value) })} className="w-full" /></label><div className="flex gap-3"><button className="flex-1 border border-safe py-2 text-safe text-[10px] uppercase">Save Project</button><button type="button" onClick={() => setShowForm(false)} className="flex-1 border border-gray-800 py-2 text-gray-500 text-[10px] uppercase">Cancel</button></div>{error && <p className="text-panic text-xs">{error}</p>}</form></div>}
  </div>;
}
